### ISSUE TITLE
Map doesn't open

### ISSUE THREAD

**Issue by Pohli** [sthocs/harbour-bikeme#6]
If I try to go to Stations Map it only writes: Could not load page

I tried with both data sources and with both map data settings.

Console output:
```
[defaultuser@Xperia10III ~]$ harbour-bikeme
[D] unknown:0 - Using Wayland-EGL
library "libutils.so" not found
library "libcutils.so" not found
library "libhardware.so" not found
library "android.hardware.graphics.mapper@2.0.so" not found
library "android.hardware.graphics.mapper@2.1.so" not found
library "android.hardware.graphics.mapper@3.0.so" not found
library "android.hardware.graphics.mapper@4.0.so" not found
library "libc++.so" not found
library "libhidlbase.so" not found
library "libgralloctypes.so" not found
library "android.hardware.graphics.common@1.2.so" not found
library "libion.so" not found
library "libz.so" not found
library "libhidlmemory.so" not found
library "android.hidl.memory@1.0.so" not found
library "vendor.qti.qspmhal@1.0.so" not found
[D] onCompleted:27 - Restoring app state: Dortmund
[W] unknown:1283 - file:///usr/lib64/qt5/qml/Sailfish/Silica/PageStack.qml:1283:13: QML AnimatedLoader: (file:///usr/share/harbour-bikeme/qml/pages/InteractiveMap.qml:3:1: module "QtLocation" is not installed
import QtLocation 5.4
^)
```
SFOS 4.5.0.24 and BikeMe 0.11.1 on Xperia 10 III

**Comment by sthocs** [comment]
Thanks for testing the app!
Indeed a missing dependency wasn't detected by Harbour QA but @vigejolla found the problem and fixed it in https://github.com/sthocs/harbour-bikeme/pull/4
I'm don't why I didn't encountered the issue when installing it on my 10 III but anyway, a fixed version has just been submitted to Harbour.

**Comment by vigejolla** [comment]
The new version is now in Harbour, so please update and try again!

**Comment by sthocs** [comment]
Thank you @vigejolla, you are a very early bird :D 
@Pohli I'll let you confirm before closing the issue, thanks!

**Comment by Pohli** [comment]
It works now, thank you very much.

**Comment by sthocs** [comment]
Great, thanks for confirming 👍
